name: inventree
description: Open Source Inventory Management System
homepage: https://inventree.org
notifications: false
buildpack: https://github.com/mjmair/heroku-buildpack-python#v177-1
env:
  - INVENTREE_DB_ENGINE=sqlite3
  - INVENTREE_DB_NAME=database.sqlite3
  - DISABLE_COLLECTSTATIC=1
targets:
  ubuntu-20.04: true
env:
  - INVENTREE_CONFIG_FILE=/opt/inventree/config.yaml
  - INVENTREE_PLUGINS_ENABLED
  - INVENTREE_STATIC_ROOT=/opt/inventree/static
  - INVENTREE_MEDIA_ROOT=/opt/inventree/media
  - INVENTREE_PLUGIN_FILE=/opt/inventree/plugins.txt
