name: inventree
description: Open Source Inventory Management System
homepage: https://inventree.org
notifications: false
targets:
  debian-11: true
  ubuntu-20.04: true
env:
  - INVENTREE_CONFIG_FILE=/opt/inventree/config.yaml
  - INVENTREE_PLUGINS_ENABLED
  - INVENTREE_STATIC_ROOT=/opt/inventree/static
  - INVENTREE_MEDIA_ROOT=/opt/inventree/media
  - INVENTREE_PLUGIN_FILE=/opt/inventree/plugins.txt
