version: "3.8"

# Docker compose recipe for InvenTree development server
# - Runs sqlite3 as the database backend
# - Uses built-in django webserver

# IMPORANT NOTE:
# The InvenTree docker image does not clone source code from git.
# Instead, you must specify *where* the source code is located,
# (on your local machine).
# The django server will auto-detect any code changes and reload the server.

services:
    # InvenTree web server services
    # Uses gunicorn as the web server
    inventree-dev-server:
        container_name: inventree-dev-server
        build:
            context: ../
            target: dev
            dockerfile: docker/Dockerfile
        environment:
            INVENTREE_DEV_VENV: "True"
        ports:
            - 8000:8000
        user: root
        volumes:
            # Ensure you specify the location of the 'INVENTREE_SRC_DIR' in the dev-config.env file
            - ${INVENTREE_SRC_DIR:?inventree_src_dir}:/home/inventree
        env_file:
            # Environment variables required for the dev server are configured in dev-config.env
            - dev-config.env

        restart: unless-stopped

        command: ["/init-server.sh", "python3", "manage.py", "runserver", "0.0.0.0:8000"]


    # Background worker process handles long-running or periodic tasks
    inventree-dev-worker:
        container_name: inventree-dev-worker
        build:
            context: ../
            target: dev
            dockerfile: docker/Dockerfile
        environment:
            INVENTREE_DEV_VENV: "True"
        depends_on:
            - inventree-dev-server
        volumes:
            # Ensure you specify the location of the 'INVENTREE_SRC_DIR' in the dev-config.env file
            - ${INVENTREE_SRC_DIR:?inventree_src_dir}:/home/inventree
        env_file:
            # Environment variables required for the dev server are configured in dev-config.env
            - dev-config.env
        restart: unless-stopped

        command: [ "/wait-for-it.sh", "--timeout=0", "inventree-dev-server:8000", "--",
                   "/init-worker.sh",
                   "python3", "manage.py", "qcluster"]

