# Netlify configuration file
# https://www.netlify.com/docs/netlify-toml-reference/

[build]
  command = "yarn run build --outDir dist"
  publish = "dist"
  base = "/platform"

# Send requests to subpath
[[redirects]]
  from = "/"
  to = "/platform"

[[redirects]]
  from = "/*"
  to = "/index.html 200"
  status = 200

[[plugins]]
  package = "@netlify/plugin-lighthouse"

  [plugins.inputs.settings]
    preset = "desktop" # Optionally run Lighthouse using a desktop configuration
