# Netlify configuration file
# https://www.netlify.com/docs/netlify-toml-reference/

[build]
  command = "yarn run build --outDir dist"
  publish = "dist"

[[plugins]]
  package = "@netlify/plugin-lighthouse"

  [plugins.inputs.settings]
    preset = "desktop" # Optionally run Lighthouse using a desktop configuration
