# Netlify configuration file
# https://www.netlify.com/docs/netlify-toml-reference/

[build]
  command = "yarn run build  --outputDir=dist"
  publish = "dist"

# Send requests to subpath
[[redirects]]
  from = "/"
  to = "/platform"
