# Backport tagged issues to a stable branch.
#
# To enable backporting for a pullrequest, add the label "backport" to the PR.
# Additionally, add a label with the prefix "backport-to-" and the target branch

name: Backport

on:
  pull_request_target:
    types: [ "labeled", "closed" ]

permissions:
  contents: write

jobs:
  backport:
    name: Backport PR
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Backport Action
        uses: korthout/backport-action@ef20d86abccbac3ee3a73cb2efbdc06344c390e5  # Pinned at v2.5.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          copy_labels_pattern: '*'
          label_pattern: 'backport-to-([^ ]+)$'
