name: Documentation Checks

on:
  push:
    branches-ignore:
      - l10*

  pull_request:
    branches-ignore:
      - l10*

jobs:

  mkdocs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Check Config
        run: |
          pip install pyyaml
          python docs/ci/check_mkdocs_config.py
      - name: Check Links
        run: |
          pip install linkcheckmd requests
          python -m linkcheckmd docs --recurse
