# Build, test and push InvenTree docker image
# This workflow runs under any of the following conditions:
#
# - Push to the master branch
# - Push to the stable branch
# - Publish release
#
# The following actions are performed:
#
# - Check that the version number matches the current branch or tag
# - Build the specified InvenTree docker image
# - Run suite of unit tests against the build image
# - Push the compiled, tested image to dockerhub

name: Docker

on:
  release:
    types: [published]

  push:
    branches:
      - 'master'
      - 'stable'

  pull_request:
    branches:
      - 'master'

jobs:

  # Build the docker image
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Extract Commit Information
        run: |
          echo "git_commit_hash=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          echo "git_commit_date=$(git show -s --format=%ci)" >> $GITHUB_ENV
      - name: Version Check
        run: |
          python3 ci/check_version_number.py
          echo "Git Commit Hash: ${{ env.git_commit_hash }}"
          echo "Git Commit Date: ${{ env.git_commit_date }}"
      #- name: Build Docker Image
      #  run: |
      #    docker-compose build
      #    docker-compose run inventree-dev-server invoke update
      #- name: Run Unit Tests
      #  run: |
      #    docker-compose up -d
      #    docker-compose run inventree-dev-server invoke wait
      #    docker-compose run inventree-dev-server invoke test
      #    docker-compose down
