# Check javascript template files

name: Javascript Templates

on:
  push:
    branches:
      - master

  pull_request:
    branches-ignore:
      - l10*

jobs:

  javascript:
    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      INVENTREE_DB_ENGINE: sqlite3
      INVENTREE_DB_NAME: inventree
      INVENTREE_MEDIA_ROOT: ./media
      INVENTREE_STATIC_ROOT: ./static
    steps:
      - name: Install node.js
        uses: actions/setup-node@v2
      - run: npm install
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install gettext
          pip3 install invoke
          invoke install
          invoke static
      - name: Check Templated Files
        run: |
          cd ci
          python check_js_templates.py
      - name: Lint Javascript Files
        run: |
          npm install eslint eslint-config-google
          invoke render-js-files
          npx eslint js_tmp/*.js