# Runs on releases

name: Publish release notes
on:
  release:
    types: [ published ]

jobs:

  stable:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # pin@v3.1.0
      - name: Version Check
        run: |
          pip install requests
          python3 ci/version_check.py
      - name: Push to Stable Branch
        uses: ad-m/github-push-action@4dcce6dea3e3c8187237fc86b7dfdc93e5aaae58 # pin@master
        if: env.stable_release == 'true'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: stable
          force: true

  publish-build:
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # pin@v3.1.0
      - name: Environment Setup
        uses: ./.github/actions/setup
        with:
          npm: true
      - name: Install dependencies
        run: cd src/frontend && yarn install
      - name: Build frontend
        run: cd src/frontend && npm run build
      - name: Zip frontend
        id: zip-frontend
        run: |
          filename="frontend-build-$(date +%s).zip"
          echo "filename=$filename" >> $GITHUB_OUTPUT
          cd InvenTree/web/static
          zip -r $filename web/
      - uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: InvenTree/web/static/${{ steps.zip-frontend.outputs.filename }}
          asset_name: frontend-build
          tag: ${{ github.ref }}
          overwrite: true
