name: Test that the packaging is working

on:
  workflow_dispatch: null
  schedule:
    - cron: "0 0 * * *"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install package
        run: |
          export SETUP_PYTHON=python3.9
          wget https://raw.githubusercontent.com/matmair/InvenTree/matmair/issue3933/contrib/install.sh && bash install.sh master matmair
          echo "native python"
          python --version
          echo "included env"
          /opt/inventree/env/bin/python --version
      - name: Test
        run: |
          wget localhost/api/
