name: Test that the packaging is working

on:
  workflow_dispatch: null
  schedule:
    - cron: "0 0 * * *"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install package
        run:
          wget https://raw.githubusercontent.com/matmair/InvenTree/matmair/issue3933/contrib/install.sh && bash install.sh master matmair
      - name: Test
        run: wget localhost/api/
