name: Test that the packaging is working

on:
  workflow_dispatch: null
  schedule:
    - cron: "0 0 * * *"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Uninstall python
        run: sudo apt-get remove --auto-remove python3.8
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Detect version
        run: python --version
      - name: Install package
        run:
          wget https://raw.githubusercontent.com/matmair/InvenTree/matmair/issue3933/contrib/install.sh && bash install.sh master matmair
      - name: Test
        run: wget localhost/api/
