name: Update dependency files regularly

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup
        run: pip install -r requirements-dev.txt
      - name: Update requirements.txt
        run: pip-compile --output-file=requirements.txt requirements.in -U
      - name: Update requirements-dev.txt
        run: pip-compile --generate-hashes --output-file=requirements-dev.txt requirements-dev.in -U
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "[Bot] Updated dependency"
          branch: dep-update
